id: 9242876a-41c4-42f8-96f8-ac92d6025406
title: Settings
data:
  site_name: 'Connor Leech'
  social:
    -
      name: Twitter
      url: 'https://twitter.com/connor11528'
      icon: site/social-icons/twitter.svg
    -
      name: Github
      url: 'https://github.com/connor11528'
      icon: site/social-icons/github.svg
    -
      name: Email
      url: 'mailto:connorleech@gmail.com'
      icon: site/social-icons/email.svg
