title: Settings
data:
  site_name: 'Connor Leech'
  social:
    -
      name: Twitter
      url: 'https://twitter.com/connor11528'
      icon: site/social-icons/twitter.svg
    -
      name: Github
      url: 'https://github.com/connor11528'
      icon: site/social-icons/github.svg
    -
      name: Email
      url: 'mailto:connorleech@gmail.com'
      icon: site/social-icons/email.svg
    -
      name: LinkedIn
      url: 'https://www.linkedin.com/in/connorleech/'
      icon: site/social-icons/linkedin.svg
